name: Check Flake Build

on:
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'config/**'
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'config/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check flake
        run: |
          nix flake check
          nix build . 
